api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    formats:                       # enable plain JSON in addition to JSON‑LD
        jsonld: ['application/ld+json']
        json:   ['application/json']
